#!/usr/bin/env bash
# =============================================================================
# make_exe.sh - build a Windows installer (.exe) for Aetherion.
#
# Counterpart to make_pkg.sh (macOS), except Microsoft didn't shake me down for
# $100/year just to NOT scare users with a SmartScreen popup. Small mercies.
#
# Bundles the app via bundle_app.sh (--platform windows), then wraps the
# resulting portable folder into a proper Windows installer using NSIS
# (`makensis`). If NSIS isn't installed (because of course it isn't, who has
# NSIS lying around?), we fall back to the portable .zip already generated by
# bundle_app.sh and exit with a clear note instead of cryptic shell errors.
#
# Usage (from the repo root, in Git Bash / MSYS2 on Windows):
#   ./make_exe.sh                       # bundle then build installer
#   ./make_exe.sh --no-bundle           # skip bundling, reuse existing folder
#   ./make_exe.sh --version 1.2.3       # override version string
#   ./make_exe.sh --output-dir dist     # write installer to dist/ instead of build/
#
# Prerequisites:
#   * Visual Studio + vcpkg build already performed (see rebuild_windows.ps1
#     or rebuild_windows.sh), so build/<Config>/blackhole-sim.exe exists.
#   * `makensis` on PATH for the actual installer step. Install via:
#         choco install nsis        (Chocolatey)
#         winget install NSIS.NSIS  (winget)
#     If absent, the script still emits the portable .zip.
#
# Output: build/Aetherion-Installer-v<VERSION>.exe   (and the .zip from bundle)
# =============================================================================
set -euo pipefail

APP_NAME="Aetherion"
PUBLISHER="Liam Nayyar"
VERSION="1.0.0"
BUILD_DIR="build"
OUTPUT_DIR=""
BUNDLE_FIRST=true
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-bundle)     BUNDLE_FIRST=false; shift ;;
        --version)       VERSION="${2:?'--version requires a value'}"; shift 2 ;;
        --version=*)     VERSION="${1#--version=}"; shift ;;
        --build-dir)     BUILD_DIR="${2:?'--build-dir requires a path'}"; shift 2 ;;
        --build-dir=*)   BUILD_DIR="${1#--build-dir=}"; shift ;;
        --output-dir)    OUTPUT_DIR="${2:?'--output-dir requires a path'}"; shift 2 ;;
        --output-dir=*)  OUTPUT_DIR="${1#--output-dir=}"; shift ;;
        -h|--help)       sed -n '2,28p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) printf 'ERROR: Unknown argument: %s\nRun with --help for usage.\n' "$1" >&2; exit 1 ;;
    esac
done

[[ -z "${OUTPUT_DIR}" ]] && OUTPUT_DIR="${BUILD_DIR}"

# ── Platform check ──────────────────────────────────────────────────────────
# No, you cannot build a Windows .exe installer from your MacBook. I know it
# would be neat. It's not happening today.
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*) ;;
    *)
        printf 'ERROR: make_exe.sh must be run on Windows (Git Bash / MSYS2).\n' >&2
        printf '       For other platforms, use make_pkg.sh (macOS) or bundle_app.sh --platform linux.\n' >&2
        exit 1
        ;;
esac

# ── Optionally produce the portable folder via bundle_app.sh ────────────────
PORTABLE_DIR="${SCRIPT_DIR}/${BUILD_DIR}/Aetherion-windows"
if $BUNDLE_FIRST; then
    echo "=== Running bundle_app.sh --platform windows ==="
    bash "${SCRIPT_DIR}/bundle_app.sh" --platform windows
fi

if [[ ! -d "${PORTABLE_DIR}" ]]; then
    printf 'ERROR: %s not found.\n' "${PORTABLE_DIR}" >&2
    printf '       Run ./bundle_app.sh --platform windows first, or omit --no-bundle.\n' >&2
    exit 1
fi
if [[ ! -f "${PORTABLE_DIR}/Aetherion.exe" ]]; then
    printf 'ERROR: %s/Aetherion.exe not found. Build the project first.\n' "${PORTABLE_DIR}" >&2
    exit 1
fi

mkdir -p "${SCRIPT_DIR}/${OUTPUT_DIR}"

# ── Locate makensis ─────────────────────────────────────────────────────────
# NSIS installs into the most predictable place imaginable on Windows, and
# also somehow never gets added to PATH. We look in both.
MAKENSIS=""
for _candidate in \
    "$(command -v makensis 2>/dev/null || true)" \
    "/c/Program Files (x86)/NSIS/makensis.exe" \
    "/c/Program Files/NSIS/makensis.exe"; do
    if [[ -n "${_candidate}" && -x "${_candidate}" ]]; then
        MAKENSIS="${_candidate}"; break
    fi
done

if [[ -z "${MAKENSIS}" ]]; then
    cat >&2 <<'WARN'

WARNING: `makensis` (NSIS compiler) was not found on PATH.
         Skipping .exe installer; the portable .zip from bundle_app.sh is still
         available under build/. To install NSIS:

             choco install nsis            (Chocolatey)
             winget install NSIS.NSIS      (winget)
             https://nsis.sourceforge.io/Download

         Then re-run: ./make_exe.sh --no-bundle
WARN
    exit 2
fi
echo "  Using NSIS: ${MAKENSIS}"

# ── Generate the NSIS script in a temp dir ──────────────────────────────────
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

NSI_FILE="${WORK_DIR}/aetherion-installer.nsi"
OUTPUT_EXE="${SCRIPT_DIR}/${OUTPUT_DIR}/${APP_NAME}-Installer-v${VERSION}.exe"

# Convert POSIX paths to Windows paths for NSIS
to_windows_path() {
    if command -v cygpath &>/dev/null; then
        cygpath -w "$1"
    else
        printf '%s' "$1"
    fi
}

PORTABLE_WIN="$(to_windows_path "${PORTABLE_DIR}")"
OUTPUT_WIN="$(to_windows_path "${OUTPUT_EXE}")"

# License: project LICENSE file or short fallback
LICENSE_SRC="${SCRIPT_DIR}/LICENSE"
if [[ ! -f "${LICENSE_SRC}" ]]; then
    LICENSE_SRC="${WORK_DIR}/LICENSE.txt"
    cat > "${LICENSE_SRC}" <<'LICENSE'
MIT License - see project repository for full terms.
LICENSE
fi
LICENSE_WIN="$(to_windows_path "${LICENSE_SRC}")"

# Optional installer icon (use AppIcon.ico if present in repo root)
ICON_LINE=""
if [[ -f "${SCRIPT_DIR}/AppIcon.ico" ]]; then
    ICON_WIN="$(to_windows_path "${SCRIPT_DIR}/AppIcon.ico")"
    ICON_LINE="Icon \"${ICON_WIN}\""
fi

cat > "${NSI_FILE}" <<NSI
; Aetherion Astrophysics Suite installer (auto-generated by make_exe.sh)
Unicode true
!include "MUI2.nsh"

Name "${APP_NAME} Astrophysics Suite"
OutFile "${OUTPUT_WIN}"
InstallDir "\$LOCALAPPDATA\\Programs\\${APP_NAME}"
InstallDirRegKey HKCU "Software\\${APP_NAME}" "InstallDir"
RequestExecutionLevel user
SetCompressor /SOLID lzma
${ICON_LINE}

VIProductVersion "${VERSION}.0"
VIAddVersionKey  "ProductName"     "${APP_NAME} Astrophysics Suite"
VIAddVersionKey  "CompanyName"     "${PUBLISHER}"
VIAddVersionKey  "FileDescription" "${APP_NAME} installer"
VIAddVersionKey  "FileVersion"     "${VERSION}"
VIAddVersionKey  "ProductVersion"  "${VERSION}"
VIAddVersionKey  "LegalCopyright"  "(c) ${PUBLISHER}"

!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "${LICENSE_WIN}"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN "\$INSTDIR\\Aetherion.exe"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

Section "Install"
    SetOutPath "\$INSTDIR"
    File /r "${PORTABLE_WIN}\\*.*"

    WriteRegStr HKCU "Software\\${APP_NAME}" "InstallDir" "\$INSTDIR"

    ; Add/Remove Programs entry
    WriteRegStr   HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "DisplayName"     "${APP_NAME} Astrophysics Suite"
    WriteRegStr   HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "DisplayVersion"  "${VERSION}"
    WriteRegStr   HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "Publisher"       "${PUBLISHER}"
    WriteRegStr   HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "DisplayIcon"     "\$INSTDIR\\Aetherion.exe"
    WriteRegStr   HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "InstallLocation" "\$INSTDIR"
    WriteRegStr   HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "UninstallString" "\$INSTDIR\\Uninstall.exe"
    WriteRegDWORD HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "NoModify" 1
    WriteRegDWORD HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "NoRepair" 1

    ; Start Menu + Desktop shortcuts
    CreateDirectory "\$SMPROGRAMS\\${APP_NAME}"
    CreateShortcut  "\$SMPROGRAMS\\${APP_NAME}\\${APP_NAME}.lnk" "\$INSTDIR\\Aetherion.exe"
    CreateShortcut  "\$SMPROGRAMS\\${APP_NAME}\\Uninstall ${APP_NAME}.lnk" "\$INSTDIR\\Uninstall.exe"
    CreateShortcut  "\$DESKTOP\\${APP_NAME}.lnk" "\$INSTDIR\\Aetherion.exe"

    WriteUninstaller "\$INSTDIR\\Uninstall.exe"
SectionEnd

Section "Uninstall"
    Delete "\$DESKTOP\\${APP_NAME}.lnk"
    Delete "\$SMPROGRAMS\\${APP_NAME}\\${APP_NAME}.lnk"
    Delete "\$SMPROGRAMS\\${APP_NAME}\\Uninstall ${APP_NAME}.lnk"
    RMDir  "\$SMPROGRAMS\\${APP_NAME}"

    DeleteRegKey HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}"
    DeleteRegKey HKCU "Software\\${APP_NAME}"

    RMDir /r "\$INSTDIR"
SectionEnd
NSI

# ── Compile the installer ───────────────────────────────────────────────────
echo "=== Compiling NSIS installer (v${VERSION}) ==="
"${MAKENSIS}" -V2 "$(to_windows_path "${NSI_FILE}")"

if [[ ! -f "${OUTPUT_EXE}" ]]; then
    printf 'ERROR: NSIS reported success but %s was not produced.\n' "${OUTPUT_EXE}" >&2
    exit 1
fi

SIZE="$(du -sh "${OUTPUT_EXE}" | cut -f1)"
printf '\n=== Done ===\n'
printf '  Installer: %s  (%s)\n' "${OUTPUT_EXE}" "${SIZE}"
printf '\n  To install:  double-click the .exe (installs to %%LOCALAPPDATA%%\\Programs\\%s, no admin needed)\n' "${APP_NAME}"
printf '  To uninstall: Settings > Apps, or run %%LOCALAPPDATA%%\\Programs\\%s\\Uninstall.exe\n' "${APP_NAME}"
printf '\n  NOTE: This installer is unsigned, because code-signing certificates cost\n'
printf '        roughly the GDP of a small island nation. Windows SmartScreen will probably\n'
printf '        sulk on first run; tell users to click "More info" -> "Run anyway".\n'
printf '        If you happen to have a real cert lying around, sign it properly:\n'
printf '            signtool sign /fd SHA256 /a /tr http://timestamp.digicert.com /td SHA256 "%s"\n' "${OUTPUT_EXE}"
